### ISSUE TITLE
self.canvas.show() error in ClassificationFrame.py

### ISSUE THREAD

**Issue by giorgio71** [Emanz93/PIClassifier#1]
Hi,
when I start a program and press "manual classification" (after Working directory selection), the program don't create a frame and exit with an exception because don't recognise the attribute .show() in "self.canvas.show()" in line 75 on file ClassificationFrame.py.

I currently use an Apple MacBook with a operation system 10.14 moyave and Python  3.7, R 3.5.1

I recently changed the operating system from 10.13.

[Error.pdf](https://github.com/Emanz93/PIClassifier/files/2454061/Error.pdf)

**Comment by Emanz93** [comment]
Hello Giorgio,
I can't duplicate the error, but let's do some tests.

Could you please try to replace the line:
`self.canvas.show()`
with:
`self.canvas.draw()`
re-run the software and see if it got stuck again.

Probably this issue is related to the new version (3.0.0) of matplotlib.

**Comment by giorgio71** [comment]
Hello,
I have made the change and the software works perfectly!!!
In fact I have updated (automatically..) matplotlib to a new version 3.0.0.

Thank you!!

**Comment by Emanz93** [comment]
Good to hear it! I have updated the software accordingly.
Enjoy classification!
