### ISSUE TITLE
dyld: Library not loaded: @rpath/libreadline.6.2.dylib

### ISSUE THREAD

**Issue by tom501** [Emanz93/PIClassifier#3]
dyld: Library not loaded: @rpath/libreadline.6.2.dylib
  Referenced from: /Users/lucatomasetti/anaconda/lib/R/lib/libR.dylib
  Reason: image not found
Abort trap: 6

Error inside Controller.py at line 289, in call_r_script:
    res_string = check_output(cmd, universal_newlines=True)

**Comment by Emanz93** [comment]
Try to follow these steps:
1) reinstall anaconda with:
`conda install anaconda-clean`
`anaconda-clean`
2) Update conda:
`conda update -c rdonnellyr -c main --all`
3) Then, open R via the terminal:
`R`
and then reinstall rpart library with the following two commands:
`remove.packages("rpart")`
`install.packages("rpart")`

**Comment by tom501** [comment]
Seems to work fine. Thank you! :)
